### PR TITLE
Add NgModule

### PR DESCRIPTION
**Pull request by escardin**
Totally didn't test this yet, but seems to address a need.

### CODE REVIEW

**Comment by chenkie** [comment]
Awesome thanks, I'll test it out when I get a sec. 

I wonder if we should name the module something else. I can imagine people might create their own `AuthModule`. What about `JwtModule`?

**Comment by escardin** [comment]
They can assign it a different name on import if they need to.

I was thinking of abandoning the Auth prefix in the 1.0 rewrite and calling everything Jwt. It would make it a little easier if all the Auth stuff breaks visibly if we don't keep it. If we do a transition period, we could rewrite the Auth bits to point at the Jwt bits instead of breaking the api or some such. It's still just a thought though. I want to see what the rewritten lib looks like before I worry too much about naming things or transitions.

**Comment by escardin** [comment]
Should fix #158

**Comment by chenkie** [comment]
@escardin I merged some other PRs and now we've got a conflict here. Can you fix it up and I'll merge? Thanks

**Comment by escardin** [comment]
Fixed up

**Pull request merged**
