### PR TITLE
Implemented expired token handler

### PR DESCRIPTION
**Pull request by vrudikov**
Implemented handler to allow custom handling logic for expired tokens. Can be used like this:

```typescript
new AuthConfig({
            ...
            expiredTokenHandler: () => {
                return new Observable<Response>((subs) => {
                    subs.complete();
                    router.navigate(['/login']);
                })
            }
        })
```

### CODE REVIEW

**Comment by vrudikov** [comment]
Anyone here?

**Comment by RaAleks** [comment]
Guys, can you provide any response on this comment? Should we wait you'r review or not.

**Comment by vrudikov** [comment]
Ping?! :)

**Comment by chenkie** [comment]
Hey thanks for your PR! sorry for the crazy delay. Looks like this is targeting pre v1. Would you want to have a look at the interceptor in v1+ and see if it could use something like this?

**Pull request closed without merging**
