### PR TITLE
Blacklist/Whitelist check fix

### PR DESCRIPTION
**Pull request by edusperoni**
We should not try to get the token if the route/domain is blacklisted. Fixes https://github.com/auth0/angular2-jwt/issues/516

### CODE REVIEW

**Comment by wslaghekke** [comment]
+1 looks good, could this get merged please?

**Comment by studds** [comment]
@chenkie any plans to merge this in?

**Comment by samschirmer** [comment]
Can someone pull this in? Kind of a big one.

**Comment by klinden** [comment]
Just adding to the thread. I'd really appreciate it as well if this could get merged.

**Comment by studds** [comment]
@damieng @joshcanhelp can this be merged in? It's been open for a very long time, kinda critical.

**Comment by damieng** [comment]
@luisrudge might be able to help here.

**Comment by elkdanger** [comment]
I'd like to get this merged in. Does anyone have a very small repro case for #516 that this PR fixes?

**Comment by stevehobbsdev** [comment]
@davidpatrick Could you stick an approval on this so we can get it merged?

**Pull request merged**
