### PR TITLE
Handle Promised TokenGetter, Issue #126

### LINKED ISSUE #126: Can't use promise within tokenGetter in
I am using Ionic 2 with a custom Store provider to get/set token data using the native SecureStorage library with a LocalStorage fallback. However, when I attempt to use said store provider to get the token, then `return` the token from the promise, it appears that the tokenGetter does not wait for the promise to be completed before attempting to process the token.

```javascript
ionicBootstrap( MyFancyApp, [
  Store,
  HTTP_PROVIDERS,
  AUTH_PROVIDERS,
  provide( AuthHttp, {
    useFactory: ( http, store ) => {
      return new AuthHttp( new AuthConfig({
        headerName: 'Authorization',
        headerPrefix: 'Bearer',
        tokenName: '',
        tokenGetter: ( () => {
          store.get('bearer').then( token => {
            console.log( token );
            return token;
          });
        }),
        globalHeaders: [{'Content-Type':'application/json'}]
      }), http );
    },
    deps: [ Http, Store ]
  })
]);
```

When I attempt to use AuthHttp to make a request, I get the following feedback in the console:
screen shot 2016-08-11 at 3 53 41 pm
It appears that the error is thrown by AuthHttp before the `token` is logged to the console, which is what leads me to think it isn't waiting for the promise. Any ideas? I'm pretty new to Angular 2 so I could just be doing this wrong. Thanks!

### PR DESCRIPTION
**Pull request by Sabartius**
With this Pull-Request the Token-Getter can return a `string `or a `Promise<string>`.
Fixes #126 

I would have liked to add some tests, but there's no test-configuration for running the available tests :(

### CODE REVIEW

**Comment by escardin** [comment]
try `npm test`

**Comment by Sabartius** [comment]
@escardin npm test doesn't test anything, because there is no karma.conf in this repository.
i get this message: `You need to include some adapter that implements __karma__.start method!`

**Comment by escardin** [comment]
Man, did that never get merged?

**Comment by escardin** [comment]
Here's the one I wrote for the tests. It's not there because the .gitignore globs all the *.js files. Please feel free to include it in your commit.

```
module.exports = function (config) {
    'use strict';

    config.set({
        basePath: './',
        frameworks: ["jasmine"],
        // list of files / patterns to load in the browser
        files: [
            {pattern: 'angular2-jwt.spec.ts', watched: false}
        ],

        // list of files / patterns to exclude
        exclude: [],

        preprocessors: {
            'angular2-jwt.spec.ts': [ 'webpack', 'sourcemap']
        },


        webpackServer: {
            noInfo: true
            //progress:false,
            //stats: false,
            //debug:false
        },

        // web server port
        port: 9876,

        // enable / disable colors in the output (reporters and logs)
        colors: true,

        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,

        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: false,

        browsers: [
            //"Firefox",
            //"Chrome",
            //"IE",
            "PhantomJS"
        ],

        // Continuous Integration mode
        // if true, it capture browsers, run tests and exit
        singleRun: true,

        reporters: ['progress'],

        webpack: {
            resolve: {
                extensions: ['', '.ts', '.js']
            },
            module: {
                loaders: [
                    {test: /\.ts$/,loader: 'awesome-typescript-loader'}
                ]
            },
            stats: {
                colors: true,
                reasons: true
            },
            debug: false,
            devtool: 'inline-source-map'
        }
    });
};

```

**Comment by Sabartius** [comment]
Thanks, commited the file and tests are starting.
But one test breaks `JwtHelper isTokenExpired should return false when the token doesn't have an expiry date FAILED`

**Comment by escardin** [comment]
They passed when I wrote them ;) I suspect there were a few changes and we have not been enforcing tests on new commits or anything like that, so it got through (just like the missing karma.conf.js)

**Comment by Sabartius** [comment]
Okay, so i'll ignore this one while implementing my tests

**Comment by Sabartius** [comment]
@escardin added some tests :)

**Comment by Sabartius** [comment]
@chenkie I think it's your turn now :)

**Comment by chenkie** [comment]
thanks for this!

**Comment by Ant59** [comment]
Can we get this working for Observables? I'd like to pull the token in from an Ngrx store.

**Comment by pbrain19** [comment]
Somehow this remains to be documented. Someone please update with all the details.

**Pull request merged**
