### PR TITLE
#30 support nodejs atob for angular 2 Universal

### PR DESCRIPTION
**Pull request by rusmaxim**

### CODE REVIEW

**Comment by rusmaxim** [comment]
#30

**Comment by chenkie** [comment]
Beauty, thank you!

**Comment by jechevarria** [comment]
I just clone the repo.
got this error:

angular2-jwt.ts(4,23): error TS2307: Cannot find module 'atob'.

**Comment by rusmaxim** [comment]
@jechevarria if you just cloned repo you need install it new dependency.

**Comment by jechevarria** [comment]
I forgot to say: when I run 'npm install' got the error.

I run:
> git clone https://github.com/auth0/angular2-jwt.git
> cd angular2-jwt
> npm install
and crash

**Comment by escardin** [comment]
Is there some way we can avoid this dependency for browser only users? we could do just atob() instead of window.atob() and atob could be defined globally or something.

**Comment by rusmaxim** [comment]
@escardin we can make function atob in AuthConfig

**Pull request merged**
