### PR TITLE
Rework request to mostly match ng2 Http API

### PR DESCRIPTION
**Pull request by escardin**
This is almost exactly the work I did when I encountered the problem with not being able to add headers.

I didn't use the authHttp api when I wrote mine.

I broke some of the api for the lesser used stuff (in the Http Api, delete and head have no body).

Considering that I already broke the api, I would suggest going a step further and replacing request with _request, and getting rid of options (not part of the http api).

### CODE REVIEW

**Comment by escardin** [comment]
fixes #2

**Comment by damienpontifex** [comment]
:+1: need this

**Comment by troyanskiy** [comment]
I should check pull requests before implementing mine the same fixes.
Definitely need that.
Please merge.

**Comment by escardin** [comment]
If you're going to do a breaking change release, I still think the api should be made to fully match http.

**Comment by chenkie** [comment]
Can you elaborate a bit more on `getting rid of options` here just so I'm clear?

> Considering that I already broke the api, I would suggest going a step further and replacing request with _request, and getting rid of options (not part of the http api).

**Comment by escardin** [comment]
When I was getting my changes into angular2-jwt I reviewed the http api and it doesn't provide an options call. I was suggesting removing it because it's not in the http api.

see: https://angular.io/docs/ts/latest/api/http/Http-class.html

I don't think it's really necessary. Extending the http api is okay (desired even). The important part is that the angular2-jwt request function is not drop in compatible with the http request function.

**Comment by chenkie** [comment]
Makes sense :+1: Thanks

**Pull request merged**
