### PR TITLE
Add options http operation support to AuthHttp

### PR DESCRIPTION
**Pull request by tyoras**
Add options http operation support to AuthHttp

### CODE REVIEW

**Comment by escardin** [comment]
When I built this, I modelled it after the base http so that it would be potentially composable (still haven't fixed the _request though). HTTP doesn't provide options: https://angular.io/docs/ts/latest/api/http/Http-class.html

I don't really have a reason not to add it, but you should file an issue with angular/http as well.

**Comment by tyoras** [comment]
I understand but actually OPTIONS is a supported RequestMethod in angular2 : https://angular.io/docs/ts/latest/api/http/RequestMethod-enum.html .

This is the RequestMethod I have used in this pull request and it is working just fine.

**Comment by escardin** [comment]
I know it's there. We're trying to be api compatible with the http class though, and the http class (which I linked) does not expose that. I think our failing in this case is that we don't expose request more than that we don't have an options function. I'll make up a PR for that now.

**Comment by tyoras** [comment]
It is fair enough, Thank you.

**Comment by charsleysa** [comment]
@escardin @tyoras angular2 now supports OPTIONS.

https://angular.io/docs/ts/latest/api/http/index/Http-class.html

**Comment by tyoras** [comment]
Good news.
So, I think this pull request is still relevant, I hope you will merge it.

**Comment by charsleysa** [comment]
@tyoras @chenkie this has been done in #132.
This PR can be closed.

**Comment by tyoras** [comment]
great, I close.

**Pull request closed without merging**
