### PR TITLE
Bump versions to support angular 6.0.0 and rxjs 6

### PR DESCRIPTION
**Pull request by ivalexa**

### CODE REVIEW

**Comment by Koslun** [comment]
@ivalexa Given that this will break any app still using Angular 4 or 5, lower than version 2.7 of TypeScript and RxJS 5.x, I think this should definitely trigger a major version bump, i.e. to version 2.x.

Should this be done inside of this PR or directly following it?

**Comment by lwensveen** [comment]
Could do that, maybe tag it as a Angular 6 compatible branch for the time being? Or maybe the other way around.

**Comment by nischi** [comment]
We need that as well. Can you tell us by when you will do a release for that?

**Comment by lwensveen** [comment]
I made a new pull request: #533 

Figured if we're doing breaking changes and doing a major version bump, we might as well update all dependencies.

Seems to work fine.

**Comment by GKephart** [comment]
When will this version of angular-jwt be available on NPM and what version will it be under?

**Comment by stevehobbsdev** [comment]
Doesn't look to me like this PR is still relevant, as Angular version inside `package.json` have already been bumped to 6.0.0. If there should be some corrections made, please feel free to raise another PR.

**Pull request closed without merging**
