### PR TITLE
chore(package.json) allow all beta versions of ng2/rx

### LINKED ISSUE #22: Error when doing authHttp.get with angular beta.1?
Hello,
I included auth0 in my angular beta.1 test project.
The login works quite well, but when I try to do an authenticated html request with
`this.authHttp.get` I get an error.

After debugging it seems to me that we are not giving the correct request parameters in the library. 
In the documentations that I looked at, |request| needs first a url string and then a options object.

Line 97: `request = this.http.request(req);` here I have the error, the req object seems fine.

Would be great to know if you also have an error or not.

In the auth0 example project it seems to work, but they have different dependencies so maybe there were some breaking changes?

UPDATE:
I followed the debugging inside angulars http.request and it seems like they try to validate if the object is a proper request object:
`else if (url instanceof static_request_1.Request) {`
This fails, is it possible something changed and the request object needs to be constructed differently?

I checked the example project the same way and here the url object is validated as a proper request.
So it seem they changed something in beta.1?

Thanks.

### PR DESCRIPTION
**Pull request by escardin**
As per: https://docs.npmjs.com/misc/semver#prerelease-tags

Should fix #22

### CODE REVIEW

**Comment by chenkie** [comment]
Thanks for looking into this! One issue is that it looks like angular2 still has a hard dependency on rxjs beta 0, so we'd need to keep it there for now.

**Comment by escardin** [comment]
@chenkie I was thinking along the lines of we're going to require at least beta0 of rx and otherwise not be specific about which one, which would make it easier for us to stay compatible with ng2, while letting them or their users specify which versions to use.

**Comment by chenkie** [comment]
I agree this would be ideal, but the problem right now is that angular2-beta.1 won't install if Rx is higher than beta.0, which is what happens when using `>=5.0.0-beta.0`. I'm wondering if this peer dependency thing will be fixed with the next Angular beta.

BTW, can you send me an email?  Can't find yours anywhere :) ryan.chenkie@auth0.com

Thanks!

**Comment by chenkie** [comment]
Updated to ng2 beta 7 and rxjs beta 2. Thanks again for this :)

**Pull request closed without merging**
