### PR TITLE
updated to use the config.tokenName when verifying the token

### PR DESCRIPTION
**Pull request by abner**
it closes the issue #265.

### CODE REVIEW

**Comment by abner** [comment]
I think i wasn't clear:

the issue is tokenNotExpired function. Is was being called on requestWithToken.
When you call `tokenNotExpired` passing undefined  it will fallback to the default tokenName to get the token if the value passed to jwt is null. I actually got in this scenario because i changed the tokenName to a custom name but i already had a expired token on localStorage with the default one, so it validated the token which wasn't the old one.

**Comment by escardin** [comment]
Okay. That's a real issue. Passing the token name isn't the right answer though. I think i'll need to rework the call to tokenNotExpired. I think it makes sense to just replace it with a simpler version and not actually use tokenNotExpired. I'm not happy with the tokenNotExpired function, and it will be replaced whenever I get around to writing 1.0

**Comment by jmls** [comment]
yah, this is broken for me too. applied the patch, start getting correct data

**Comment by sschocke** [comment]
I ran into this problem as well, after updating to the newer version of this where the default token name has changed. This leaves me with 2 options. Change my code everywhere to use the default new tokenName instead, or update this one line and it fixes everything.

I don't see how implementing this breaks anything, so why can't it be done until such time as you get around to replacing tokenNotExpired(), because at the moment it's a broken library if you don't use the default tokenName

**Comment by sschocke** [comment]
btw, @escardin , I get what you are saying regarding passing the JWT token into `tokenNotExpired`. If you do that, the `tokenName` parameter is irrelevant, as it should just validate the passed token. The real problem here is that the JWT token is `undefined` in the `requestWithToken` function, and that is causing the `tokenNotExpired` function to fall back to reading the token from **localStorage** using `tokenName`

My guess is that something regarding setting the "getter" function in the AuthConfig constructor is not working correctly when using a custom tokenName, but this patch does "fix" the problem until such time as the root cause can be addressed.

**Pull request closed without merging**
