### PR TITLE
Update for compatibility with angular2 rc5

### PR DESCRIPTION
**Pull request by charsleysa**
- Fixed issues with building for Typescript 2
- Fixed issue with empty body causing exceptions when global header is used (usually for setting Content-Type: application/json)
- Formatted code following most common TSLint settings

### CODE REVIEW

**Comment by chenkie** [comment]
Thanks for your PR :) To build this with `typescript@next` I needed to put `<any>` back in on line 105. Otherwise I get this: `error TS7017: Index signature of object type implicitly has an 'any' type`.

If we are to build this with TypeScript 2, doesn't that mean that individual Angular 2 projects are going to also need to use TS 2? If that's the case, then I don't think we can go there yet. The reason I ask is that I'm seeing errors when testing against an existing project. Things like:

`error TS7017: Index signature of object type implicitly has an 'any' type`
`error TS1112: A class member cannot be declared optional`

**Comment by charsleysa** [comment]
@chenkie I've made some changes so that both Typescript@latest and Typescript@next work.

As for building with Typescript 2, Angular2 will be using Typescript 2 when it is officially released AFAIK.

One of the issues I faced was that this library was breaking my build as it was still shipped using the raw Typescript instead of shipping the compiled JavaScript and Typescript Declaration files.

This means that my project's tsconfig.json file is being applied to the Typescript in this library and my project's configuration contains structNullChecks set to true which fails on this library.

I have worked around this issue in the latest commit I just made which is backward compatible and shouldn't cause any issues with existing projects.

**Comment by Mielpops54** [comment]
Hi,

Is it possible to merge this PR on master please ? :) 
The release of my project depends on these changes.

**Comment by chenkie** [comment]
Thanks for your work on this @charsleysa

**Pull request merged**
