### PR TITLE
Do not default to true on error during domain whitelist verification

### LINKED ISSUE #437: IE11 - Missing URL constructor leads to false-positive whitelist check
I've experience this problem with `angular2-jwt 1.0.0-beta.9`.

Because the URL constructor is not available in IE11, [jwt.interceptor.ts line 41](https://github.com/auth0/angular2-jwt/blob/v1.0/src/jwt.interceptor.ts#L41) throws an exception. 

This results in `isWhitelistedDomain` returning `true` for all inputs. 

I would expect the exception to be rethrown, to make the developer aware of the fact that a polyfill is required and the requests are not sent to remote site.

### PR DESCRIPTION
**Pull request by fourcube**
This prevents false-positive whitelist checks in IE11. (fixes #437).

### CODE REVIEW

**Comment by fourcube** [comment]
@chenkie this is a security issue for IE11 users and I think it should be fixed / merged asap.

**Comment by montella1507** [comment]
@fourcube  i dont think this is the correct fix.. i do not see any reason why it should be implemented with try..catch block if there is no problem to implement it correctly. You are fixing only one of the problems (big +1 for you).  

This way you are saying "if anything fails during security check - add token to request" and this is super wrong. Dont you see that?

**Comment by fourcube** [comment]
@montella1507 you are correct. I'll update the pull request.

It would be great if the original author could verify if the try/catch is actually required (but I cannot see why at the moment).

**Comment by montella1507** [comment]
@fourcube  thank yoou very much. I think there was try.. catch meant primary because possible wrong RegEXP in whitelisted domains.

You may cancel this PR of yours:
https://github.com/auth0/angular2-jwt/pull/439

**Comment by DaveXCS** [comment]
@montella1507 
where was a try catch to fix crashes with relative urls as in the deleted comment mentioned.
```
catch (err) {
      // if we're here, the request is made
       // to the same domain as the Angular app
       // so it's safe to proceed
       return true;
     }
```
it would be better to check if the url is relative instead of using a try catch workaround. but to delete this try catch is causing definitely a big problem.

**Comment by montella1507** [comment]
LOL no.  Sending user tokens to foreign server is 1000x bigger issue than your application is crashing.

**Comment by DaveXCS** [comment]
A non working app is always safer than a working one 👎 
So your solution is to make any unsafe application crashing?

As i said a good solution would be to check the url if its relative or not and proceed but you should be more careful by removing code which had a reason. But to improve the existing code is always a good idea.

**Comment by montella1507** [comment]
@DaveXCS  YES, not working app is way better than unsafe - when you realize you are in a prison because of disposing data of your users, will be that moment when you will realize i was right.

i do not insist on that solution - (for example) beta.10 is not working with NG5 in IE11, but it is better to crash (here you can fix that problem), than silently sent Bearer token to foreign server.

**Pull request merged**
