### PR TITLE
Upgrade angular to v11

### PR DESCRIPTION
**Pull request by celian-garcia**
Hi, thanks for this library, I'm planning to update progressively until Angular v13, with one commit by Angular version (one for v11, on for v12, one for v13). I plan to move linter to eslint in the Angular v12 commit.
Please tell me if you agree with these changes and thus if I can continue or not. 

The objective is at the end to get rid of the warning in v13 https://github.com/auth0/angular2-jwt/issues/712

Cheers!

### Changes

- Upgraded Angular to v11 using ``ng update``

### References

- Probably fixes this https://github.com/auth0/angular2-jwt/issues/697, even though I think it works perfectly with Angular 11 as we ran our frontend on Angular 11 without issue for monthes.

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All code quality tools/guidelines in the [CONTRIBUTING documentation](https://github.com/auth0/open-source-template/blob/master/CONTRIBUTING.md) have been run/followed
- [x] All relevant assets have been compiled as directed in the [CONTRIBUTING documentation](https://github.com/auth0/open-source-template/blob/master/CONTRIBUTING.md), if applicable

### CODE REVIEW

**Comment by PedroS5499** [comment]
why this taking so long?

**Comment by celian-garcia** [comment]
> why this taking so long?
I agree it's a bit long, I'm wondering if it's still maintained. To be honest I'm considering making a fork.

Hello @Sambego, sorry I mention you as you are the last commiter.  I'd like to remind you the fact that Angular 10 is not anymore an LTS, and so doesn't receive any security updates, according to the [Angular Support Policy](https://angular.io/guide/releases#support-policy-and-schedule) documentation.
image

If Auth0 still uses this project, it should be updated for sure!

**Comment by PedroS5499** [comment]
No no, no stale

**Comment by celian-garcia** [comment]
@PedroS5499 did you find a substitute ? I don't want to maintain a fork so I will search for another lib or maybe integrate stuff in my code place.

**Comment by frederikprijck** [comment]
Closing this in favor of https://github.com/auth0/angular2-jwt/issues/712

**Pull request closed without merging**
