### PR TITLE
Workaround for UMD issues with Node in Webpack 4

### PR DESCRIPTION
**Pull request by ceph3us**
Fixes https://github.com/auth0/angular2-jwt/issues/543.
See https://github.com/webpack/webpack/issues/6522#issuecomment-371120689 for reasoning.

### CODE REVIEW

**Comment by DanLatimer** [comment]
Would be great to get this merged, I'm running into the same issue

**Comment by cybercyst** [comment]
I also would appreciate this being merged :smile:

**Comment by DanLatimer** [comment]
@cybercyst fyi my terrible work around till this is in is to copy the .ts files from this project into my project 😳

It's terrible but let's me continue work while I wait for the fix

**Comment by ceph3us** [comment]
For those of you in the mean time who'd prefer an npm based stopgap solution, I have released a fork of this package with the fix as `@melonwd/angular-jwt` version `2.0.0-hotfix1`.

**Comment by dneeleman** [comment]
Any updates on this?

**Comment by vance** [comment]
Any way this can get merged?

**Comment by vance** [comment]
Uh, seems like the `auth0/angular-jwt@1.1.0` works gain with angular 6.0.6

**Pull request merged**
