### PR TITLE
add a constructor to AuthHttpError class

### PR DESCRIPTION
**Pull request by FabienDehopre**
This fixes the issue #160

### CODE REVIEW

**Comment by chenkie** [comment]
Thanks for this. Tests are passing?

**Comment by FabienDehopre** [comment]
I did run the command ```npm run test``` and all the tests executed successfully.

**Comment by FabienDehopre** [comment]
In fact, this will not solve the issue for the moment because it seems that browsers don't allow extending built-in class for the moment.
See these issues in TypeScript repo:
https://github.com/Microsoft/TypeScript/issues/7639
https://github.com/Microsoft/TypeScript/issues/1168

**Comment by escardin** [comment]
Perhaps something like this? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Custom_Error_Types

**Comment by jostschmithals** [comment]
I had solved the problem by modifying the extension in the source code like this (but I saw this discussion only now):

```
export class AuthHttpError extends Error {  
  constructor(message) {  
    super(message);  
    this.message = message;  
  }  
}
```

For me this simple solution works in all browsers.

**Pull request closed without merging**
