### PR TITLE
rxjs updated to new version

### PR DESCRIPTION
**Pull request by onerizafer**

### CODE REVIEW

**Comment by vapits** [comment]
Angular 2.4.0 requires a minimum `^5.0.1` version for `rxjs` so this will not solve the issue.

**Comment by alexduros** [comment]
I started in a fork to port to angular ^2.3.1 

https://github.com/alexduros/angular2-jwt

but I came with this error when I use angular2-jwt in my project.

```
ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 80:22 in the original .ts file), resolving symbol AUTH_PROVIDERS 
````

**Comment by BrainCrumbz** [comment]
Hello all. How can we contribute to upgrade this project to most recent *rxjs* (5.0.2 as of today)?

**Comment by escardin** [comment]
@BrainCrumbz I think there are a few PRs floating around already. Just need @chenkie to merge one or make a new one and push it out.

**Comment by chenkie** [comment]
#259 has this fix plus some others. Closing this in favor of it.

**Pull request closed without merging**
